### ISSUE TITLE
is this fetch-installed-software supported within win 7?

### ISSUE THREAD

**Issue by gumuruhsspj** [deventio7/fetch-installed-software#2]
I tried to execute the following code, but found no output at all...

```
window.win32 = require('fetch-installed-software');
var v = win32.getAllInstalledSoftware();
console.log(v);
```

**Comment by deventio7** [comment]
I don't have an Win7 machine at the moment, so I'm afraid I can't specifically test that. However, it looks like you're trying to console.log the async version; try `getAllInstalledSoftwareSync()` instead for your use case.

(The default `getAllInstalledSoftware()` method actually returns a promise of an array of objects, not an array of objects as written in the outdated Readme. I'll update that later when I have some time.)
