### ISSUE TITLE
cant use module with node-ipc module in same project

### ISSUE THREAD

**Issue by si458** [deventio7/fetch-installed-software#3]
Hi All,
im not sure whats going on but i cant use `fetch-installed-software` and `node-ipc` modules together in the same project?
for some reason the node-ipc module is calling the removeFirst function inside fetch-installed-software so it crashes with an error?
```
PS C:\Users\Simon\Documents\ourmonitoring\nodejs> node .\test.js
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.SIMON055A
starting server on  /tmp/app.SIMON055A 
starting TLS server false
starting server as Unix || Windows Socket
C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\fetch-installed-software\win32.js:18
         ^
TypeError: this.shift is not a function
    at Server.Array.removeFirst (C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\fetch-installed-software\win32.js:18:10)
    at Server.emit (C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\event-pubsub\es5.js:74:21)
    at Server.onStart (C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\node-ipc\dao\socketServer.js:41:14)
    at Object.onceWrapper (events.js:481:28)
    at Server.emit (events.js:375:28)
    at emitListeningNT (net.js:1354:10)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
SAMPLE CODE BELOW
```
const software = require('fetch-installed-software');
const ipc = require('node-ipc');
ipc.serve(function () {
    ipc.server.on('connect', function () {
        console.log('Connection to IPC');
    });
});
ipc.server.start();
runcode = async()=>{
    var installed = await software.getAllInstalledSoftware();
    console.log(installed);
}
runcode();

**Comment by si458** [comment]
my patch should fix the issue as the array prototype isnt required #4

**Comment by deventio7** [comment]
Fixed by merge of #4.

**Comment by si458** [comment]
Thanks @deventio7!
I forgot to update the json for a new version 🙁 
Can you push this to npmjs as a new version?

**Comment by deventio7** [comment]
Yup, just pushed as `0.0.7`. Sorry about that, haven't been paying attention to this package for a long time, so it skipped my mind, haha.

**Comment by si458** [comment]
> Yup, just pushed as `0.0.7`. Sorry about that, haven't been paying attention to this package for a long time, so it skipped my mind, haha.

Thank you and no worries!

It's an amazing module! Just what I was looking for as I only require windows altho I am looking at maybe trying to add the Linux/Mac bits in...
